apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
spec:
  tls:
    - hosts:
        - 44-197-210-246.nip.io
      secretName: nextcloud-tls
  rules:
    - host: 44-197-210-246.nip.io