apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "PLACEHOLDER_ROOT_PASSWORD"
  MYSQL_PASSWORD: "PLACEHOLDER_DB_PASSWORD"
  MYSQL_USER: "nextcloud"
  MYSQL_DATABASE: "nextcloud"
  NEXTCLOUD_ADMIN_USER: "admin"
  NEXTCLOUD_ADMIN_PASSWORD: "PLACEHOLDER_ADMIN_PASSWORD"