apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          env:
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: staging.34-200-119-27.nip.io